
int Attack[MAXLEN][MAXLEN]={\
          0   1   2   3   4   5   6   7   8    9  10  11  12  13  14  15  16  
    0     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    1     NOP,NOP,NOP,NOP,NOP,RIG,DOW,RIG,NOP,NOP,DOW,NOP,NOP,NOP,NOP,NOP,NOP,
    2     NOP,NOP,NOP,NOP,NOP,NOP,DOW,NOP,NOP,NOP,DOW,NOP,NOP,NOP,NOP,NOP,NOP,
    3     NOP,NOP,NOP,NOP,NOP,NOP,DOW,NOP,NOP,NOP,DOW,NOP,NOP,NOP,NOP,NOP,NOP,
    4     NOP,NOP,NOP,NOP,NOP,NOP,DOW,NOP,NOP,NOP,DOW,NOP,NOP,NOP,NOP,NOP,NOP,
    5     NOP,RIG,RIG,ORD,DOW,NOP,RIG,RIG,RIG,RIG,DOW,NOP,RIG,RIG,RIG,DOW,NOP,
    6     NOP,OUD,NOP,RIG,RIG,RIG,RIG,OLR,OLR,RIG,RIG,RIG,ORU,OUD,NOP,NOP,NOP,
    7     NOP,RIG,RIG,UPP,NOP,UPP,UPP,NOP,NOP,NOP,NOP,NOP,NOP,RIG,RIG,UPP,NOP,
    8     NOP,NOP,OUD,RIG,OUD,NOP,DOW,NOP,NOP,NOP,NOP,RIG,RIG,OUD,NOP,NOP,NOP,
    9     NOP,RIG,RIG,DOW,NOP,DOW,DOW,NOP,DOW,DOW,DOW,DOW,NOP,RIG,RIG,DOW,NOP,
   10     NOP,OUD,NOP,RIG,RIG,RIG,RIG,ORD,ORD,RIG,RIG,RIG,ORD,OUD,NOP,NOP,NOP,
   11     NOP,RIG,RIG,ORU,UPP,NOP,RIG,RIG,RIG,RIG,UPP,NOP,RIG,RIG,RIG,UPP,NOP,
   12     NOP,NOP,NOP,NOP,NOP,NOP,UPP,UPP,UPP,NOP,UPP,RIG,UPP,NOP,NOP,NOP,NOP,
   13     NOP,NOP,NOP,NOP,NOP,NOP,UPP,NOP,UPP,NOP,UPP,NOP,NOP,NOP,NOP,NOP,NOP,
   14     NOP,NOP,NOP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,NOP,NOP,NOP,
   15     NOP,NOP,NOP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,NOP,NOP,NOP,
    };
int Escape[MAXLEN][MAXLEN]={\
          0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  
    0     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    1     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    2     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    3     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    4     NOP,NOP,NOP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,UPP,NOP,NOP,NOP,NOP,NOP,NOP,
    5     NOP,NOP,NOP,NOP,NOP,NOP,UPP,LEF,LEF,LEF,UPP,NOP,DOW,RIG,NOP,LEF,NOP,
    6     NOP,NOP,NOP,NOP,NOP,NOP,UPP,LEF,LEF,LEF,UPP,LEF,UPP,RIG,NOP,UPP,NOP,
    7     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,RIG,RIG,UPP,NOP,
    8     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    9     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,DOW,RIG,DOW,NOP,
   10     NOP,NOP,NOP,NOP,NOP,NOP,DOW,LEF,LEF,LEF,DOW,LEF,DOW,DOW,NOP,DOW,NOP,
   11     NOP,NOP,NOP,NOP,NOP,NOP,DOW,LEF,LEF,LEF,DOW,NOP,UPP,UPP,NOP,LEF,NOP,
   12     NOP,NOP,NOP,NOP,NOP,NOP,DOW,NOP,NOP,NOP,DOW,NOP,NOP,NOP,NOP,NOP,NOP,
   13     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
   14     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
   15     NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,NOP,
    };
